chore: add extra optimization to the macaron-base image
Signed-off-by: Trong Nhan Mai <trong.nhan.mai@oracle.com>

diff --git a/docker/Dockerfile.base b/docker/Dockerfile.base
--- a/docker/Dockerfile.base
+++ b/docker/Dockerfile.base
@@ -1,49 +1,48 @@
 # Copyright (c) 2022 - 2023, Oracle and/or its affiliates. All rights reserved.
 # Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.
 
+# This Dockerfile is for building the base image which contains the necessary components
+# to build and run the Macaron Docker image.
+# This image is based on the container-registry.oracle.com/os/oraclelinux:9-slim image and has the main components:
+#   Python3.11.2 (with pip 22.3.1 and setuptools 65.5.1) compiled and installed from source.
+#   Oracle JDK 17 installed from dnf.
+#   Souffle 2.3 compiled and installed from source.
+#   Other runtime libraries (e.g sqlite-devel) which are installed from dnf.
+
 FROM container-registry.oracle.com/os/oraclelinux:9-slim
 
 ENV HOME="/home/macaron" \
+    # Setting Python related environment variables.
     PYTHON3_VERSION=3.11.2 \
     PYTHONUNBUFFERED=1 \
     PYTHONDONTWRITEBYTECODE=1 \
-    # http://bugs.python.org/issue19846
-    # > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L12
     LANG="C.UTF-8" \
-    # The GPG key to verify the source tar ball
-    # following the instructions on https://www.python.org/downloads/
-    PYTHON_SOURCE_GPG="A035C8C19219BA821ECEA86B64E628F8D684696D"
+    # The GPG key to verify the source tar ball following the instructions in https://www.python.org/downloads/
+    PYTHON_SOURCE_GPG="A035C8C19219BA821ECEA86B64E628F8D684696D" \
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L133
+    PYTHON_PIP_VERSION=22.3.1 \
+    PYTHON_SETUPTOOLS_VERSION=65.5.1 \
+    PYTHON_GET_PIP_URL="https://github.com/pypa/get-pip/raw/d5cb0afaf23b8520f1bbcfed521017b4a95f5c01/public/get-pip.py" \
+    PYTHON_GET_PIP_SHA256="394be00f13fa1b9aaa47e911bdb59a09c3b2986472130f30aa0bfaf7f3980637" \
+    # Setting Java related environment variables.
+    JAVA_HOME="/usr/lib/jvm/jdk-17-oracle-x64" \
+    PATH=/usr/local/bin:/usr/lib/jvm/jdk-17-oracle-x64/bin:$PATH
 
-ENV PATH=/usr/local/bin:$PATH
-
-# INSTALLING RUNTIME DEPENDENCIES.
+# We run the installation of all components in one single RUN to minimize the final image size.
 RUN : \
     && set -eux \
-    && microdnf upgrade -y \
+# ---------------------------------------------------------------------------------------------------------------------
+    # INSTALL RUNTIME DEPENDENCIES.
     && microdnf install -y \
-        # These are the runtime dependencies as specified by the official Python 3.11 slim-buster Dockerfile.
-        # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L17
-        # We couldn't find the equivalent of netbase in Oracle Linux.
-        # netbase
-        tzdata \
-        ca-certificates \
-        # We switch to dnf as the dnf mark command is not available in microdnf.
+        # We switch to dnf to use some features of dnf that do not exist in microdnf.
         dnf \
+    # We can then safely remove the unused microdnf.
     && dnf remove -y microdnf \
-    && dnf clean all \
-    && rm -rf /var/cache/yum \
-    && rm -rf /var/cache/dnf
-
-# INSTALLING PYTHON3.11 and PIP.
-RUN : \
-    && set -eux \
-    # Store the list of user installed packages so that we could preserve it when we clean up unused packages.
-    # https://dnf.readthedocs.io/en/latest/command_ref.html#history-command
-    && USER_MANUAL_INSTALLED="$(dnf history userinstalled | tail -n +2)" \
-    # We add an extra yum repo that contains the package lcov.
-    # We are following the convention as existing repo definitions in OL9.
-    # The following yum repo will be resolved to this URL in OL9:
+    # Add the EPEL packages yum repo following the convention as existing repo definitions in OL9.
+    # The following yum repo will be resolved to this URL:
     #       https://yum.oracle.com/repo/OracleLinux/OL9/developer/EPEL/x86_64/index.html
+    # This repo contains the package lcov which is later used in building Python from source.
     && echo -e \
 "\
 [ol9_epel]\n\
@@ -54,46 +53,75 @@ gpgcheck=1\n\
 enabled=1\
 " >> /etc/yum.repos.d/epel-ol9.repo \
     # We clean all here so that when we run upgrade, the newly added yum repo is used.
-    && dnf clean all \
-    && dnf upgrade -y \
-    # The ol9_core_ready_builder repo has already been defined and it is enabled for the package:
-    #       gdbm-devel
+    && dnf clean all    \
+    && dnf upgrade -y   \
+    && dnf install -y   \
+        # These are the runtime dependencies as specified by the official Python 3.11 slim-buster Dockerfile.
+        # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#LL19C2-L23C5
+        # Exception: netbase (We couldn't find an equivalent in Oracle Linux).
+        tzdata          \
+        ca-certificates \
+        # git and finutils are needed for running and building Macaron.
+        git             \
+        findutils       \
+        # Runtime libraries for Souffle. These are based on
+        # https://souffle-lang.github.io/build#software-requirements
+        # https://github.com/souffle-lang/souffle/blob/cc8ea091721fcfb60bed45a0edf571ad9d0c58a5/CMakeLists.txt#LL442C39-L442C129
+        # Exceptions (not installed):
+        #   mcpp - The package mcpp is not available oracle linux 9. However, we don't use Souffle's feature
+        #       that needs it.
+        #   python3 - We use the installed Python3.11.2 for this.
+        gcc-c++         \
+        libffi          \
+        libffi-devel    \
+        ncurses-devel   \
+        sqlite-devel    \
+        zlib-devel      \
+        # Oracle JDK17
+        https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm \
+    # Store the list of user installed packages so that we could preserve it when we clean up unused packages.
+    # https://dnf.readthedocs.io/en/latest/command_ref.html#history-command
+    && USER_MANUAL_INSTALLED="$(dnf history userinstalled | tail -n +2)" \
+# ---------------------------------------------------------------------------------------------------------------------
+    # INSTALL PYTHON FROM SOURCE.
+    # We enable the ol9_core_ready_builder repo for the package gdbm-devel
     && dnf --enablerepo=ol9_codeready_builder install -y \
-        # Install Python build dependencies.
-        # References:
-        #       https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L34
-        # Note that these packages are available on the yum repos in OL9 (which is based on Redhat). Therefore, it might be different
-        # when used on other Linux based (for Debian-based Linux, please see the link above).
-        autoconf       \
-        bluez-libs     \
-        bzip2-devel    \
-        expat-devel    \
-        libdb-devel    \
-        libffi-devel   \
-        libuuid-devel  \
-        gcc            \
-        gdbm-devel     \
-        glibc-devel    \
-        gnupg          \
-        gpm-devel      \
-        lcov           \
-        make           \
-        ncurses-devel  \
-        openssl-devel  \
-        pkgconfig      \
-        readline-devel \
-        sqlite-devel   \
-        tk-devel       \
-        wget           \
-        xz             \
-        xz-devel       \
-        zlib-devel     \
-        # The dpkg-dev package is used to query for used shared libraries.
-        # References:
-        #       https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L34
-        #       https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L114
-        dpkg-dev      \
+        # Install Python build dependencies. These libraries are not needed during runtime and should be removed after
+        # the build complete.
+        # The required packages are listed here:
+        #   https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L34
+        # Note that the link above describes the packages in Debian-based Linux distribution. The packages below might
+        # has different names because we are running in Oracle Linux (which is based on RedHat).
+        autoconf        \
+        bluez-libs      \
+        bzip2-devel     \
+        expat-devel     \
+        libdb-devel     \
+        libffi-devel    \
+        libuuid-devel   \
+        gcc             \
+        gdbm-devel      \
+        glibc-devel     \
+        gnupg           \
+        gpm-devel       \
+        lcov            \
+        make            \
+        ncurses-devel   \
+        openssl-devel   \
+        pkgconfig       \
+        readline-devel  \
+        sqlite-devel    \
+        tk-devel        \
+        wget            \
+        xz              \
+        xz-devel        \
+        zlib-devel      \
+        # The dpkg-dev package is used to query for used shared libraries:
+        #   https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L34
+        #   https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L114
+        dpkg-dev        \
     # Download the source tarball and verify its integrity.
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L56
     && wget -O python.tar.xz "https://www.python.org/ftp/python/$PYTHON3_VERSION/Python-$PYTHON3_VERSION.tar.xz" \
     && wget -O python.tar.xz.asc "https://www.python.org/ftp/python/$PYTHON3_VERSION/Python-$PYTHON3_VERSION.tar.xz.asc" \
 	&& GNUPGHOME="$(mktemp -d)" \
@@ -103,6 +131,7 @@ enabled=1\
 	&& command -v gpgconf > /dev/null && gpgconf --kill all || : \
 	&& rm -rf "$GNUPGHOME" python.tar.xz.asc \
     # Compile and install Python from source.
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#LL56C2-L99C3
     && mkdir -p /usr/src/python \
 	&& tar --extract --directory /usr/src/python --strip-components=1 --file python.tar.xz \
 	&& rm python.tar.xz \
@@ -123,8 +152,6 @@ enabled=1\
 		"EXTRA_CFLAGS=${EXTRA_CFLAGS:-}" \
 		"LDFLAGS=${LDFLAGS:-}" \
 		"PROFILE_TASK=${PROFILE_TASK:-}" \
-# https://github.com/docker-library/python/issues/784
-# prevent accidental usage of a system installed libpython of the same version
     && rm python \
 	&& make -j "$nproc" \
 		"EXTRA_CFLAGS=${EXTRA_CFLAGS:-}" \
@@ -134,63 +161,28 @@ enabled=1\
 	&& make install \
 	&& cd / \
 	&& rm -rf /usr/src/python \
+    # Clean up test and cache files.
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#LL100C2-L108C3
 	&& find /usr/local -depth \
 		\( \
 			\( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
 			-o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \
 		\) -exec rm -rf '{}' + \
 	&& ldconfig \
-    # We mark all unecessary packages to be removed while preserving the user installed packages.
-    # We must exclude protected packages because we couldn't remove it.
-	&& dnf list installed | tail -n +2 | cut -d' ' -f1 | xargs -r dnf mark remove > /dev/null \
-    && [ -z "$USER_MANUAL_INSTALLED" ] || dnf mark install $USER_MANUAL_INSTALLED \
-    # Look for share libraries that are used by looking through the executables in /usr/local.
-    # Reference:
-    #       https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L111
-    && find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
-		| awk '/=>/ { print $(NF-1) }' \
-		| sort -u \
-		| xargs -r dpkg-query --search \
-		| cut -d: -f1 \
-		| sort -u \
-		| xargs -r dnf mark install \
-    # Running dnf autoremove will remove all packages that are marked with "dnf mark remove".
-    # https://dnf.readthedocs.io/en/latest/command_ref.html#autoremove-command
-	&& dnf autoremove -y \
-    && dnf clean all \
-    && rm -rf /var/cache/yum \
-    && rm -rf /var/cache/dnf \
-    && python3 --version
-
-# Make some useful symlinks that are expected to exist ("/usr/local/bin/python" and friends).
-RUN : \
-    && set -eux \
+    && python3 --version \
+    # Create useful symlinks for python related tools.
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#L124
 	&& for src in idle3 pydoc3 python3 python3-config; do \
 		dst="$(echo "$src" | tr -d 3)"; \
 		[ -s "/usr/local/bin/$src" ]; \
 		[ ! -e "/usr/local/bin/$dst" ]; \
 		ln -svT "$src" "/usr/local/bin/$dst"; \
-	done
-
-# Installing pip this way will results in a smaller image size comparing to
-# installing with --ensure-pip.
-ENV PYTHON_PIP_VERSION=22.3.1 \
-    # https://github.com/docker-library/python/issues/365
-    PYTHON_SETUPTOOLS_VERSION=65.5.1 \
-    # https://github.com/pypa/get-pip
-    PYTHON_GET_PIP_URL="https://github.com/pypa/get-pip/raw/d5cb0afaf23b8520f1bbcfed521017b4a95f5c01/public/get-pip.py" \
-    PYTHON_GET_PIP_SHA256="394be00f13fa1b9aaa47e911bdb59a09c3b2986472130f30aa0bfaf7f3980637"
-
-RUN : \
-    && set -eux \
-	&& USER_MANUAL_INSTALLED="$(dnf history userinstalled | tail -n +2)" \
-	&& dnf upgrade -y \
-	&& dnf install -y wget findutils \
+	done \
+# ---------------------------------------------------------------------------------------------------------------------
+	# INSTALL PIP AND SETUPTOOLS
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#LL147C2-L166C15
 	&& wget -O get-pip.py "$PYTHON_GET_PIP_URL" \
 	&& echo "$PYTHON_GET_PIP_SHA256 *get-pip.py" | sha256sum -c - \
-	&& dnf list installed | tail -n +2 | cut -d' ' -f1 | xargs -r dnf mark remove > /dev/null \
-	&& [ -z "$USER_MANUAL_INSTALLED" ] || dnf mark install $USER_MANUAL_INSTALLED > /dev/null \
-	&& dnf autoremove -y \
 	&& python get-pip.py \
 		--disable-pip-version-check \
 		--no-cache-dir \
@@ -199,34 +191,14 @@ RUN : \
 		"setuptools==$PYTHON_SETUPTOOLS_VERSION" \
 	&& rm -f get-pip.py \
 	\
-    && dnf clean all \
-    && rm -rf /var/cache/yum \
-    && rm -rf /var/cache/dnf \
-	&& pip --version
-
-# INSTALLING SOUFFLE
-# The instructions to build Souffle in Oracle Linux is referenced from:
-#       https://github.com/souffle-lang/souffle/blob/master/.github/images/oraclelinux-8/Dockerfile
-RUN : \
-    && set -eux \
+	&& pip --version \
+# ---------------------------------------------------------------------------------------------------------------------
+    # INSTALLING SOUFFLE FROM SOURCE.
+    # Based on https://github.com/souffle-lang/souffle/blob/master/.github/images/oraclelinux-8/Dockerfile.
+    # However, some parts are different on Oracle Linux 9.
     && mkdir /souffle-src \
     && cd /souffle-src \
-    && dnf upgrade -y \
-    # Runtime dependencies for Souffle.
-    # https://github.com/souffle-lang/souffle/blob/cc8ea091721fcfb60bed45a0edf571ad9d0c58a5/CMakeLists.txt#LL442C39-L442C129
-    && dnf --enablerepo=ol9_codeready_builder install -y \
-        gcc-c++ \
-        libffi \
-        libffi-devel \
-        # The package mcpp could not be found anywhere in available oracle linux 9 repos. However, we can still run Souffle without it.
-        # mcpp
-        ncurses-devel \
-        # Souffle needs a Python3 installation. Because we already have Python3.11 installed, Souffle will pick that up.
-        # python39 \
-        sqlite-devel \
-        zlib-devel \
-    && USER_MANUAL_INSTALLED="$(dnf history userinstalled | tail -n +2)" \
-    # The build dependencies.
+    # Install build dependencies.
     && dnf --enablerepo=ol9_codeready_builder install -y \
         autoconf \
         automake \
@@ -246,34 +218,29 @@ RUN : \
     && cmake -S . -B build -DSOUFFLE_DOMAIN_64BIT=ON -DCMAKE_INSTALL_PREFIX="/usr/local" \
     && nproc="$(nproc)" \
     && cmake --build build --target install -j "$nproc" \
-    && dnf list installed | tail -n +2 | cut -d' ' -f1 | xargs -r dnf mark remove > /dev/null \
-	&& [ -z "$USER_MANUAL_INSTALLED" ] || dnf mark install $USER_MANUAL_INSTALLED > /dev/null \
-    # We exclude systemd-udev because one of the build dependencies for Souffle pull this protected package.
-    # This command make sure that it won't break if systemd-udev is not pulled in the future.
-    && (dnf list installed systemd-udev && dnf mark install systemd-udev || true) \
-	&& dnf autoremove -y \
     && cd / \
     && rm -rf /souffle-src \
-    && dnf clean all \
-    && rm -rf /var/cache/yum \
-    && rm -rf /var/cache/dnf \
-    && souffle --version
-
-# INSTALLING MACARON RUNTIME DEPENDENCIES AND OTHER UTILITIES PACKAGES.
-#   - java-17-openjdk-devel
-#   - git
-#   - findutils
-ENV JAVA_HOME="/usr/lib/jvm/jdk-17-oracle-x64"
-
-ENV PATH=$JAVA_HOME/bin:$PATH
-
-RUN : \
-    && set -eux \
-    && dnf upgrade -y \
-    && dnf install -y \
-        https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm \
-        git \
-        findutils \
+    && souffle --version \
+# ---------------------------------------------------------------------------------------------------------------------
+    # CLEANING UP.
+    # We mark all unecessary packages to be removed while preserving the user installed packages.
+	&& dnf list installed | tail -n +2 | cut -d' ' -f1 | xargs -r dnf mark remove > /dev/null \
+    && [ -z "$USER_MANUAL_INSTALLED" ] || dnf mark install $USER_MANUAL_INSTALLED \
+    # Look for share libraries that are used by looking through the executables in /usr/local to preserve them.
+    # https://github.com/docker-library/python/blob/f568f56f28fab0fe87b34db777e2c2861cef002b/3.11/slim-buster/Dockerfile#LL111C2-L121C3
+    && find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
+		| awk '/=>/ { print $(NF-1) }' \
+		| sort -u \
+		| xargs -r dpkg-query --search \
+		| cut -d: -f1 \
+		| sort -u \
+		| xargs -r dnf mark install \
+    # We exclude systemd-udev because currently one of the build dependencies for Souffle pull this protected package.
+    # This command make sure that it won't break if systemd-udev is not pulled in the future.
+    && (dnf list installed systemd-udev && dnf mark install systemd-udev || true) \
+    # Running dnf autoremove will remove all packages that are marked with "dnf mark remove".
+    # https://dnf.readthedocs.io/en/latest/command_ref.html#autoremove-command
+	&& dnf autoremove -y \
     && dnf clean all \
     && rm -rf /var/cache/yum \
     && rm -rf /var/cache/dnf \
